version: '3.8'

services:
  mqtt-broker:
    build:
      context: mqtt
      args:
        MQTT_USER: ${MQTT_USER:-admin}
        MQTT_PWD: ${MQTT_PWD:-admin}
    #network_mode: host
    user: "1000:1000"
    ports:
      - "1883:1883"
      - "9001:9001"

volumes:
  postgres_data:
  scalers:
